name: Free RDP with Cloudflare

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Cloudflared
        run: |
          curl -L -o cloudflared.exe https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe

      - name: Run Cloudflared Tunnel
        run: |
          Start-Process -NoNewWindow -FilePath "cloudflared.exe" -ArgumentList "tunnel --url http://localhost:3389"

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Show Info
        run: |
          echo "âœ… RDP Enabled!"
          echo "ðŸ‘‰ Tunnel URL logs me upar dikh raha hoga."
